.PHONY: clean

all: 	
	rm -f producer
	rm -f consumer
	g++ -o producer producer.cc
	g++ -o consumer consumer.cc

producer:   	
	g++ -o producer producer.cc
consumer:   	
	g++ -o consumer consumer.cc
clean:
	rm -f producer
	rm -f consumer

